// LAW 

LAW_STATE_IN_PROGRESS = 1;
LAW_STATE_CLOSED = 2;

LAW_TYPE_USER = 1;
LAW_TYPE_CONGRESS = 2;

LAW_COUNCILOR_VOTE_IN_FAVOR = 1;
LAW_COUNCILOR_VOTE_AGAINST = 2;
LAW_COUNCILOR_VOTE_ABSTENTION = 0;

// NOTIFICATIONS

NOTIFICATION_STATE_NO_VIEW = 1;
NOTIFICATION_STATE_VIEW = 2

NOTIFICATION_TYPE_USER_LAW_CLOSED = 1;
NOTIFICATION_TYPE_USER_LAW_VOTES = 2;
NOTIFICATION_TYPE_CONGRESS_LAW_CLOSED = 3;
NOTIFICATION_TYPE_CONGRESS_LAW_VOTES = 4;
NOTIFICATION_TYPE_USER_LAW_WITH_COMMENTS = 5;
NOTIFICATION_TYPE_CONGRESS_LAW_WITH_COMMENTS = 6;